apps/user/urls.py
from django.urls import path

from apps.user.views import (
    UserRegistrationView, IndexPageView,
    CabinetView)

app_name = "user"

urlpatterns = [
    path('accounts/register/', UserRegistrationView.as_view(), name="register"),
    path('accounts/cabinet/', CabinetView.as_view(), name='profile'),
    path('', IndexPageView.as_view(), name='index'),

]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.products.urls', namespace='products_space')),
    path('products/cart/', include('cart.urls', namespace='cart')),
    path('products/orders/', include('apps.orders.urls', namespace='orders')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('users/', include('apps.user.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/1base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>{% block title %}FOOD SHOP{% endblock %}</title>
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
</head>
<body>
<div id="header">
    <a href="/" class="logo">FOOD SHOP</a>
</div>
<div id="subheader">
    <div class="cart">
        {% with total_items=cart|length %}
            {% if cart|length > 0 %}
                Ваша карзина:
                    <a href="{% url 'cart:cart_detail' %}">
                        {{ total_items }} item{{ total_items|pluralize }},
                        ${{ cart.get_total_price }}
                    </a>
            {% else %}
                Ваша карзина пуста.
            {% endif %}
        {% endwith %}
    </div>
</div>
<div id="content">
{% block content %}
{% endblock %}
</div>
</body>
</html>

templates/2index.html
{% block content %}
    <div>
        {% if user.is_authenticated %}
            <p>Welcome, {{ user.username }}. Thanks for logging in.</p>
        {% else %}
            <p>Welcome, new user. Please log in.</p>
            <a href="{%  url 'login' %}">Login</a>
        {% endif %}

        {% if user.is_authenticated and  user.is_staff %}
            <a href="{% url 'user:register' %}"> Зарегистрировать пользователя</a>
        {% endif %}
        <p></p>
    </div>
{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Index page</title>
</head>
<body>
    <div>
        {% if user.is_authenticated %}
            <p>Welcome, {{ user.username }}. Thanks for logging in.</p>
        {% else %}
            <p>Welcome, new user. Please log in.</p>
            <a href="{%  url 'login' %}">Login</a>
        {% endif %}

        {% if user.is_authenticated and  user.is_staff %}
            <a href="{% url 'user:register' %}"> Зарегистрировать пользователя</a>
        {% endif %}
        <p></p>
    </div>
</body>
</html>

templates/index2.html
{% block content %}
    <div>
        {% if user.is_authenticated %}
            <p>Welcome, {{ user.username }}. Thanks for logging in.</p>
        {% else %}
            <p>Welcome, new user. Please log in.</p>
            <a href="{%  url 'login' %}">Login</a>
        {% endif %}

        {% if user.is_authenticated and  user.is_staff %}
            <a href="{% url 'user:register' %}"> Зарегистрировать пользователя</a>
        {% endif %}
        <p></p>
    </div>
{% endblock %}